# Generated by Django 6.0.3 on 2026-04-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('note_type', models.CharField(choices=[('text', 'Text'), ('checklist', 'Checklist')], default='text', max_length=10)),
                ('color', models.CharField(choices=[('default', 'Default'), ('coral', 'Coral'), ('peach', 'Peach'), ('sand', 'Sand'), ('sage', 'Sage'), ('fog', 'Fog'), ('storm', 'Storm'), ('dusk', 'Dusk')], default='default', max_length=10)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_checked', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='notes.note')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
