# Generated by Django 6.0.3 on 2026-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='preview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
